### PR TITLE
Data inserting from xml file using Jaxb was generated

### LINKED ISSUE #4: Add Xml parsing

### PR DESCRIPTION
**Pull request by vpetrovaa**

### CODE REVIEW

**Review by h1alexbel — COMMENTED** [review]
@vpetrovaa 
I don't understand why we need this XML file with users on the server. It would be better to fetch data from the database and then transform it into XML.
Maybe I miss something.

**Comment by vpetrovaa** [comment]
@h1alexbel, ok, will it be a good solution to make endpoint with xml file request param and than parse it to User class and save in db?

**Comment by h1alexbel** [comment]
@vpetrovaa try it

**Comment by vpetrovaa** [comment]
@h1alexbel, done

**Review by h1alexbel — APPROVED** [review]
cheers!

**Pull request merged**
